# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-23 13:40
from __future__ import unicode_literals

import apps.db_admin._resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_file', models.FileField(upload_to=apps.db_admin._resume.models.resume_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
