# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_admin', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('auth_user', models.CharField(blank=True, max_length=255, null=True)),
                ('forwarded_for', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('host_app', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.CharField(blank=True, max_length=15, null=True)),
                ('lon', models.CharField(blank=True, max_length=15, null=True)),
                ('isp', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_geo', models.CharField(blank=True, max_length=50, null=True)),
                ('date_visited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
