# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=100)),
                ('message_text', models.TextField()),
                ('message_sent', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
