# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180120_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feat_order',
            field=models.SmallIntegerField(default=99),
        ),
    ]
