# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_feat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_timeline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
