# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_project_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills2',
            field=models.ManyToManyField(related_name='ProjectSkills', to='main.Skill'),
        ),
    ]
