# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_skills2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
    ]
