# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_project_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skills2',
            new_name='skills',
        ),
    ]
