# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180125_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='order',
            field=models.SmallIntegerField(default=9),
        ),
    ]
