# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 12:43
from __future__ import unicode_literals

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to=apps.main.models.skill_logo_directory_path),
        ),
    ]
