# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180216_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
