# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180219_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
