# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
